### ISSUE TITLE
Dice roller command

### ISSUE THREAD

**Issue by fado** [fado/PyMUD#1]
Add a command that allows the user to roll an arbitrary number of dice with modifiers.

**Comment by TemporalSentinel** [comment]
i swear i'll do this eventually

**Comment by TemporalSentinel** [comment]
https://github.com/fado/PyMUD/pull/26 adds required functionality, as soon as we figure out getting input to and feeding results back to the user this can be properly plumbed in.

**Comment by fado** [comment]
Closed by [this](https://github.com/fado/PyMUD/commit/531885578aabd2f1391aff5165014441ec97c3df) commit.
