### ISSUE TITLE
Player's name is always saved as lower-case

### ISSUE THREAD

**Issue by fado** [fado/PyMUD#20]
Ensure that the player's name is always capitalized.

**Comment by aguiarcandre** [comment]
Hi @fado! Can I take this one? If I got it right, it needs to capitalize the first command received by a new player.
https://github.com/fado/PyMUD/blob/8b5d312398440d174ffd32f1af1e63dd2bdf59c4/simplemud.py#L64-L66

**Comment by fado** [comment]
Yes, please go for it.  Couple of things:

- This project is intended to get a group of our friends who are new to programming collaborating together on something.  It's more of a learning exercise than trying to build a good general purpose MUD.
- We'll be moving fairly slow.
- We don't want any one person doing too much work.

If you're okay with the above, we'd be happy for you to contribute.  (Also I should really put all that into the README at some point.)

**Comment by aguiarcandre** [comment]
No problems at all for me! I'm learning and actually this is my first PR, I'm glad to help 😄

**Comment by fado** [comment]
Closed by [this](https://github.com/fado/PyMUD/commit/71f96082a9628eb9cdca894c43890defd9abd5c4) commit.
